spring.application.name=ImagesUpload
#spring.datasource.url=jdbc:sqlserver://DESKTOP-7J2PC64\\SQLMASTER;databaseName=the_vault;encrypt=false;trustServerCertificate=true
spring.datasource.url=jdbc:sqlserver://SUPPORT-1\\MASTERSQL;databaseName=the_vault;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#------------------------------Size of file defined here-----------------------------------
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#--------------------------Storage type--------------------------------
storage.type=DATABASE

#Local File Storage Configuration =====
# storage.type=LOCAL
# app.upload.dir=uploads/

logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type=ERROR